name: Deploy to Foundry Hub
on:
  # release:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'docs/**'
    # this disables the workflow
    #branches-ignore:
    #  - '**'

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Modify build config
        run: node ./.github/workflows/foundryHubConfig.js
      - name: Install Packages
        run: |
          npm install -g @vue/cli
          npm install
      - name: Build Application
        run: |
          npm run build
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FOUNDRYHUB_SSH_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.FOUNDRYHUB_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.FOUNDRYHUB_REMOTE_USER }}
          TARGET: ${{ secrets.FOUNDRYHUB_REMOTE_TARGET }}
